// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJbCgtVT4TkA2vq7gQEyP1yco-s0HdFeI',
    appId: '1:954517266462:web:9157c7563005327a42ce0f',
    messagingSenderId: '954517266462',
    projectId: 'infin8-second',
    authDomain: 'infin8-second.firebaseapp.com',
    storageBucket: 'infin8-second.appspot.com',
    measurementId: 'G-T7N3X71M0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC851PUqgj9JizKWAcPKThZjBTOG-75Hv0',
    appId: '1:954517266462:android:6e03316ebde402a942ce0f',
    messagingSenderId: '954517266462',
    projectId: 'infin8-second',
    storageBucket: 'infin8-second.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9kbHmkc2Oalsx4VVs1FIDzMtpbB00fS8',
    appId: '1:954517266462:ios:d37658174df2a44842ce0f',
    messagingSenderId: '954517266462',
    projectId: 'infin8-second',
    storageBucket: 'infin8-second.appspot.com',
    iosClientId: '954517266462-4vq39ammg6gmn95rh73fev1fa2rlfahk.apps.googleusercontent.com',
    iosBundleId: 'com.example.scannerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9kbHmkc2Oalsx4VVs1FIDzMtpbB00fS8',
    appId: '1:954517266462:ios:d37658174df2a44842ce0f',
    messagingSenderId: '954517266462',
    projectId: 'infin8-second',
    storageBucket: 'infin8-second.appspot.com',
    iosClientId: '954517266462-4vq39ammg6gmn95rh73fev1fa2rlfahk.apps.googleusercontent.com',
    iosBundleId: 'com.example.scannerApp',
  );
}
